### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
For your [RFP with F-Droid](https://gitlab.com/fdroid/rfp/-/issues/2185) – this is what the Issuebot complained about. Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to built upon (e.g. add per-release changelogs, or replace the screenshots – what is included with this PR is what is used in my repo, where your app will [become available](https://apt.izzysoft.de/fdroid/index/apk/com.berdik.letmedowngrade) with the next sync today around 6 pm UTC), and my [formatting hints](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) if you need to change `full_description.txt`. Should you have any questions on this, just ask and I try to answer them.

### CODE REVIEW

**Comment by DavidBerdik** [comment]
As was the case for the MACsposed one, this was very helpful. Thank you!

**Comment by IzzySoft** [comment]
Glad to help! Just a short side-note on the short-description: the "dot" at the end is, by our "style guides", left out. If you have the summary inside the YAML (where it originally was), the bot will complain about. Funnily, it does not complain when it's in Fastlane or Triple-T – so :man_shrugging: as you like :wink:

So: Thanks for merging and updating! Enabled this as well in my repo and triggered a manual update. Should you one day add a featureGraphic please let me know to enable that as well, if your apps are still in my repo then (while on it: once they are listed at F-Droid, do you want me to keep them in my repo? Default is that I remove them after a decent overlap. [Some background here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ).

**Comment by DavidBerdik** [comment]
> Glad to help! Just a short side-note on the short-description: the "dot" at the end is, by our "style guides", left out. If you have the summary inside the YAML (where it originally was), the bot will complain about. Funnily, it does not complain when it's in Fastlane or Triple-T – so 🤷‍♂️ as you like 😉

Oh, I wasn't aware of that! Although I probably should have been. Even though it does not seem to matter, I can still update it for consistency if you think that would be worthwhile!

> So: Thanks for merging and updating! Enabled this as well in my repo and triggered a manual update. Should you one day add a featureGraphic please let me know to enable that as well, if your apps are still in my repo then (while on it: once they are listed at F-Droid, do you want me to keep them in my repo? Default is that I remove them after a decent overlap. [Some background here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ).

You're welcome! 😁 I haven't added a feature graphic mostly because I haven't thought of what would make a good one. I have this which I use on Google Play (or will use if Google ever stops holding the app in their review queue 🙄), but I don't really think it counts for much since it's just the app icon again: https://github.com/DavidBerdik/Let-Me-Downgrade/blob/master/play-store-images/feature-graphic.png

As for if you should leave the app in your repo, I don't have a problem with you leaving it there until you think it's time to remove it! It helps give the app exposure, which I think is great!

**Comment by IzzySoft** [comment]
> I can still update it for consistency if you think that would be worthwhile!

No urgency with that – it's currently mixed anyway. But if you adjust descriptions at some point for an update, you could do this along.

> I haven't added a feature graphic

It's not mandatory. I'd consider it mostly a "gimmick": if you have a good one, it will add to a good first impression (being shown as background at the top of the app details in the client). Otherwise, most people won't even notice there is none. So I fully agree to only add one if it's good – because a bad one certainly would be noticed :stuck_out_tongue_closed_eyes:

> I have this which I use on Google Play

Good enough I'd say! But of course your decision. If you want me to add it, just say so (or add it to Fastlane and let me know I shall pick it up). If not, it's fine as well, no worries!

> As for if you should leave the app in your repo

I usually remove an app about 10 days after it became available at F-Droid.org – unless there was special request from the author to keep it (for whatever reason), or the app is so small that it doesn't really matter (there are some with around 100kB still). I'd say people first look at F-Droid.org and only after that into my repo, so for exposure it won't matter much; main thing really is faster updates (for the price of potential signature confusion, as F-Droid signs itself). So you say – I follow :smile:

**Comment by DavidBerdik** [comment]
> No urgency with that – it's currently mixed anyway. But if you adjust descriptions at some point for an update, you could do this along.

It was a small enough change that I just did it now for both this repo and MACsposed.

> Good enough I'd say! But of course your decision. If you want me to add it, just say so (or add it to Fastlane and let me know I shall pick it up). If not, it's fine as well, no worries!

Well thanks! I decided to add the feature graphic to fastlane for both this repo and MACsposed so it is consistent with what I use on Google Play.

> I usually remove an app about 10 days after it became available at F-Droid.org – unless there was special request from the author to keep it (for whatever reason), or the app is so small that it doesn't really matter (there are some with around 100kB still). I'd say people first look at F-Droid.org and only after that into my repo, so for exposure it won't matter much; main thing really is faster updates (for the price of potential signature confusion, as F-Droid signs itself). So you say – I follow 😄

Fair enough. 😆 Honestly, I like the idea of having the app accessible on as many different platforms as possible so I would certainly vote for leaving it there as well, but if you tend to follow a 10 day rule for it, I would be fine with it being removed as well.

**Comment by IzzySoft** [comment]
> I like the idea of having the app accessible on as many different platforms as possible so I would certainly vote for leaving it there as well

You just need to say so. I've linked you the pros and cons – so if this is still your preference, I'll honor it. Reading between the lines I take it that's what you'd really like to have, and the second part is just the wish to not "violate" any rules. Now, the rules are clear: You say you want it to stay, I check and confirm it can be done – so it is configured to stay. Should I have misinterpreted your statement, or you re-decide at some point: just let me know, and I'll adjust accordingly :smile: [See](https://apt.izzysoft.de/fdroid/index/apk/com.berdik.letmedowngrade)? Note added. Same for MACsposed I take it – done as well. Including both featureGraphics.

**Comment by DavidBerdik** [comment]
Haha yes your interpretation that I would really like it to stay is correct both for this and for MACsposed! 😁

**Pull request merged**
